package com.langleague.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExerciseOptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseOptionAllPropertiesEquals(ExerciseOption expected, ExerciseOption actual) {
        assertExerciseOptionAutoGeneratedPropertiesEquals(expected, actual);
        assertExerciseOptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseOptionAllUpdatablePropertiesEquals(ExerciseOption expected, ExerciseOption actual) {
        assertExerciseOptionUpdatableFieldsEquals(expected, actual);
        assertExerciseOptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseOptionAutoGeneratedPropertiesEquals(ExerciseOption expected, ExerciseOption actual) {
        assertThat(actual)
            .as("Verify ExerciseOption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseOptionUpdatableFieldsEquals(ExerciseOption expected, ExerciseOption actual) {
        assertThat(actual)
            .as("Verify ExerciseOption relevant properties")
            .satisfies(a -> assertThat(a.getOptionText()).as("check optionText").isEqualTo(expected.getOptionText()))
            .satisfies(a -> assertThat(a.getIsCorrect()).as("check isCorrect").isEqualTo(expected.getIsCorrect()))
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseOptionUpdatableRelationshipsEquals(ExerciseOption expected, ExerciseOption actual) {
        assertThat(actual)
            .as("Verify ExerciseOption relationships")
            .satisfies(a -> assertThat(a.getExercise()).as("check exercise").isEqualTo(expected.getExercise()));
    }
}
