package com.langleague.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GrammarAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrammarAllPropertiesEquals(Grammar expected, Grammar actual) {
        assertGrammarAutoGeneratedPropertiesEquals(expected, actual);
        assertGrammarAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrammarAllUpdatablePropertiesEquals(Grammar expected, Grammar actual) {
        assertGrammarUpdatableFieldsEquals(expected, actual);
        assertGrammarUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrammarAutoGeneratedPropertiesEquals(Grammar expected, Grammar actual) {
        assertThat(actual)
            .as("Verify Grammar auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrammarUpdatableFieldsEquals(Grammar expected, Grammar actual) {
        assertThat(actual)
            .as("Verify Grammar relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContentMarkdown()).as("check contentMarkdown").isEqualTo(expected.getContentMarkdown()))
            .satisfies(a -> assertThat(a.getExampleUsage()).as("check exampleUsage").isEqualTo(expected.getExampleUsage()))
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrammarUpdatableRelationshipsEquals(Grammar expected, Grammar actual) {
        assertThat(actual)
            .as("Verify Grammar relationships")
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()));
    }
}
