package com.langleague.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VocabularyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVocabularyAllPropertiesEquals(Vocabulary expected, Vocabulary actual) {
        assertVocabularyAutoGeneratedPropertiesEquals(expected, actual);
        assertVocabularyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVocabularyAllUpdatablePropertiesEquals(Vocabulary expected, Vocabulary actual) {
        assertVocabularyUpdatableFieldsEquals(expected, actual);
        assertVocabularyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVocabularyAutoGeneratedPropertiesEquals(Vocabulary expected, Vocabulary actual) {
        assertThat(actual)
            .as("Verify Vocabulary auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVocabularyUpdatableFieldsEquals(Vocabulary expected, Vocabulary actual) {
        assertThat(actual)
            .as("Verify Vocabulary relevant properties")
            .satisfies(a -> assertThat(a.getWord()).as("check word").isEqualTo(expected.getWord()))
            .satisfies(a -> assertThat(a.getPhonetic()).as("check phonetic").isEqualTo(expected.getPhonetic()))
            .satisfies(a -> assertThat(a.getMeaning()).as("check meaning").isEqualTo(expected.getMeaning()))
            .satisfies(a -> assertThat(a.getExample()).as("check example").isEqualTo(expected.getExample()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVocabularyUpdatableRelationshipsEquals(Vocabulary expected, Vocabulary actual) {
        assertThat(actual)
            .as("Verify Vocabulary relationships")
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()));
    }
}
